language: dart
dist: xenial
addons:
  apt:
    packages:
    - lib32stdc++6
install:
- git clone https://github.com/flutter/flutter.git -b stable
- "./flutter/bin/flutter doctor"
script:
- "./flutter/bin/flutter build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
os:
- linux
deploy:
  provider: releases
  api_key:
    secure: HDalmh2JuNAG5ANziapCSkDvAnzAN/AycY13++tosNWAp/kYWwo6CSQFdbWGXVcduOlTmCJw0HLohwREZaiDIfLB0h6P4e9/EjWbluUcrHQljECbeOwn2EeqaagdxfTiSmJo6Qvl25b18CjMJ3ycP1BY2buT3w/4euud6LRf7TFTtPOmx4CD7CSQXe6bNcVtniu62WKkty/9ECifKhSNXA4LNvbtIcnzDrdXG9PKonIzGP+IazDMnCJK9Cfza5r8oR/UgNkwdwbinsEaogKvGnYjEETMgapxXRX3t7iT8qJzOajnzBxeU0RItN2yEFiSOHOK6B0TN2sHuRFEtxgrrwMJFka3gxdlnMtGkhSun6qWM2UQu5XEu24eQKxAua4TEuwHyNxoC6h2ONdCDxOpcoYFPqckDQf4XBh0yTrmTgy+EODq3yNVEbotzE5sO1lxMgIcXYgXjieNHXCdNCSWbY5owBMz/7zNTcP1fAXvbItFpPyDKA+j5bNpPqjBz2HRvBqYkxu9qoNR6pFzxAv439cyr8Mpkj9+ka6gqS77GCf/m7X7bnFqqTt8B9ILQdMZid+PZAaDEy1KFkZFoeB1vdnr0Eu8zs/f6b3SFdSk3adlVVDPrbJXHBvproZ4jj7z8OTUyf9RmxQSdQSuDlRW26U4bUj2kLx2WQMUARQhHXY=
  file: "./build/app/outputs/flutter-apk/app-release.apk"
  on:
    repo: Skelebot/hackaton
    tags: true
  skip_cleanup: 'true'
