name: jedzdobrze
description: Aplikacja Jedz Dobrze

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  provider: any
  path_provider: any
  csv: any
  image_picker_gallery_camera: any
  screenshot: any

  extended_image: any

  simple_ocr_plugin: 0.1.1
  woozy_search: ^2.0.0
  diacritic: ^0.1.1

  image: ^2.1.18

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.8.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: #222222

flutter:
  assets:
    - assets/values.csv
    - assets/icon/icon.png
    - assets/logo.png

  uses-material-design: true